DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS audit_log;
CREATE TABLE users (id INT PRIMARY KEY, name VARCHAR(100));
CREATE TABLE audit_log (id INT AUTO_INCREMENT PRIMARY KEY, action VARCHAR(100));